version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
